/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/CustomKnob`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/DrawerItem`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/EventDetailsModal`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/EventModal`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/LocationPickerModal`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/ModalWrapper`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/ReminderItem`; params?: Router.UnknownInputParams; } | { pathname: `/src/database/DatabaseService`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/CalendarScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/MapScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/params`; params?: Router.UnknownInputParams; } | { pathname: `/src/styles/styles`; params?: Router.UnknownInputParams; } | { pathname: `/src/utils/dateUtils`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/CustomKnob`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/DrawerItem`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/EventDetailsModal`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/EventModal`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/LocationPickerModal`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/ModalWrapper`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/ReminderItem`; params?: Router.UnknownOutputParams; } | { pathname: `/src/database/DatabaseService`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/CalendarScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/MapScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/params`; params?: Router.UnknownOutputParams; } | { pathname: `/src/styles/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/src/utils/dateUtils`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/src/components/CustomKnob${`?${string}` | `#${string}` | ''}` | `/src/components/DrawerItem${`?${string}` | `#${string}` | ''}` | `/src/components/EventDetailsModal${`?${string}` | `#${string}` | ''}` | `/src/components/EventModal${`?${string}` | `#${string}` | ''}` | `/src/components/LocationPickerModal${`?${string}` | `#${string}` | ''}` | `/src/components/ModalWrapper${`?${string}` | `#${string}` | ''}` | `/src/components/ReminderItem${`?${string}` | `#${string}` | ''}` | `/src/database/DatabaseService${`?${string}` | `#${string}` | ''}` | `/src/screens/CalendarScreen${`?${string}` | `#${string}` | ''}` | `/src/screens/MapScreen${`?${string}` | `#${string}` | ''}` | `/src/screens/params${`?${string}` | `#${string}` | ''}` | `/src/styles/styles${`?${string}` | `#${string}` | ''}` | `/src/utils/dateUtils${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/CustomKnob`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/DrawerItem`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/EventDetailsModal`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/EventModal`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/LocationPickerModal`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/ModalWrapper`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/ReminderItem`; params?: Router.UnknownInputParams; } | { pathname: `/src/database/DatabaseService`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/CalendarScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/MapScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/params`; params?: Router.UnknownInputParams; } | { pathname: `/src/styles/styles`; params?: Router.UnknownInputParams; } | { pathname: `/src/utils/dateUtils`; params?: Router.UnknownInputParams; };
    }
  }
}
